FROM alpine:3.11
LABEL Maintainer="Adrian Nöthlich <docker@promasu.tech>"
LABEL Description="Lightweight container with Limesurvey, Nginx 1.16 & PHP-FPM 7.3 based on Alpine Linux. (TrafeX/docker-php-nginx)"

RUN apk --no-cache add php7 nginx supervisor curl

RUN apk --no-cache add php7-fpm php7-zip php7-ldap php7-imap php7-opcache php7-pdo_pgsql php7-pgsql \
    php7-pdo php7-json php7-openssl php7-curl php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader \
    php7-ctype php7-session php7-simplexml php7-mbstring php7-gd

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf
# Remove default server definition
RUN rm /etc/nginx/conf.d/default.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY config/php.ini /etc/php7/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN mkdir -p /var/www/html
RUN mkdir -p /var/www/simplesamlphp

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /var/www/html && \
  chown -R nobody.nobody /run && \
  chown -R nobody.nobody /var/lib/nginx && \
  chown -R nobody.nobody /var/log/nginx

VOLUME /var/www/html

USER nobody

WORKDIR /var/www/html

COPY --chown=nobody html /var/www/html
COPY --chown=nobody simplesamlphp /var/www/simplesamlphp
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping
